#!/usr/bin/env node
/**
 * Reads .env (never sent to the browser) and writes public/js/config.js
 * (a plain, non-secret value the browser is allowed to see).
 *
 * We deliberately avoid a dotenv dependency so `npm install` isn't required
 * just to boot the frontend — this is a ~15-line .env parser.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'public', 'js', 'config.js');

function parseEnv(text) {
  const out = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

if (!fs.existsSync(ENV_PATH)) {
  console.error(
    '[build:config] No .env file found. Copy .env.example to .env first:\n' +
      '  cp .env.example .env'
  );
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(ENV_PATH, 'utf8'));

const host = env.API_HOST || 'localhost';
const port = env.API_PORT || '4000';
const basePath = (env.API_BASE_PATH || '').replace(/\/$/, '');
const apiBaseUrl = `http://${host}:${port}${basePath}`;

const banner =
  '// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.\n' +
  '// Re-run `npm run build:config` after changing .env.\n' +
  '// Safe for the browser: contains only a base URL, no secrets.\n';

const contents =
  banner +
  `window.__APP_CONFIG__ = Object.freeze({\n` +
  `  API_BASE_URL: ${JSON.stringify(apiBaseUrl)},\n` +
  `});\n`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, contents, 'utf8');
console.log(`[build:config] Wrote ${path.relative(ROOT, OUT_PATH)} -> API_BASE_URL=${apiBaseUrl}`);
